spring:
  application:
    name: plant-finder
  profiles:
    include: private
  data:
    mongodb:
      uri: mongodb+srv://admin:R7x3uBDzsmQNC14x@cluster0.ai8o1gq.mongodb.net/union?retryWrites=true&w=majority
